[package]
name = "tcpp03-m20"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "Driver for the TCPP03-M20 USB-C power delivery controller"

[dependencies]
bitfield = "0.19.5"
defmt = { version = "1.1.1", optional = true }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
device-driver = { version = "1.0.*", features = ["dsl"] }
thiserror = "2.0.20"
displaydoc = "0.2.7"

[features]
default = []
defmt = ["dep:defmt", "embedded-hal/defmt-03", "embedded-hal-async/defmt-03"]